workspace:
  base: /test
  path: oe_multilingual

services:
  web:
    image: fpfis/php71-build:latest
    environment:
     - DOCUMENT_ROOT=/test/oe_multilingual
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  frpc-tunnel:
    image: fpfis/drone-frpc-plugin:latest
    when:
      event: [ push, tag ]
    secrets: [ frpc_token, frpc_server ]
    environment:
      - PLUGIN_ENDPOINT=web:8080
      - PLUGIN_GEN_AUTH=yes
      - PLUGIN_DOMAIN=oe_multilingual-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}.ci.fpfis.tech.ec.europa.eu
      - PLUGIN_URL_OUTPUT_FILE=/test/oe_multilingual/.frpc

matrix:
  DRUPAL_VERSION:
    - 8.6.x

pipeline:

  composer-install:
    image: fpfis/php71-build
    volumes:
      - /cache:/cache
    commands:
      - composer require webflo/drupal-core-require-dev:${DRUPAL_VERSION=8.6.x}

  npm-build:
    image: node:9.5.0
    commands:
      - cd build/themes/contrib/oe_theme
      - npm install --unsafe-perm
      - npm run build

  site-install:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run drupal:site-setup
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/behat
