<?php

/**
 * @file
 * The OpenEuropa Multilingual URL suffix module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Routing\TrustedRedirectResponse;
use Drupal\oe_multilingual_url_suffix\Hook\OeMultilingualUrlSuffixHooks;
use Drupal\redirect\Entity\Redirect;

/**
 * Implements hook_language_types_info_alter().
 *
 * Fixes the suffix-based language negotiation plugin for the URL type of
 * language. This basically changes the default URL-based language negotiation
 * plugin set by core (LanguageNegotiationUrl). This is needed because we cannot
 * configure the language negotiation for the URL type via the UI (only content
 * and interface). And there are subsystems in core (such as the language
 * manager) that rely exclusively on the URL type.
 *
 * @see \language_language_types_info_alter()
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function oe_multilingual_url_suffix_language_types_info_alter(array &$language_types) {
  return \Drupal::service(OeMultilingualUrlSuffixHooks::class)->languageTypesInfoAlter($language_types);
}

/**
 * Implements hook_redirect_response_alter().
 *
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function oe_multilingual_url_suffix_redirect_response_alter(TrustedRedirectResponse $response, Redirect $redirect) {
  return \Drupal::service(OeMultilingualUrlSuffixHooks::class)->redirectResponseAlter($response, $redirect);
}
