<?php

/**
 * @file
 * Contains hooks to manipulate language links for selection page.
 */

declare(strict_types = 1);

use Drupal\Core\Language\LanguageInterface;
use Drupal\language\Plugin\LanguageNegotiation\LanguageNegotiationUrlFallback;
use Drupal\oe_multilingual_url_suffix\Plugin\LanguageNegotiation\LanguageNegotiationUrlSuffix;

/**
 * Implements hook_language_types_info_alter().
 *
 * This implemented hook will make Drupal aware of a new method
 * of determining the Url language and will make the Url Suffix negotiator
 * behave the same way as the core Url negotiator.
 *
 * For more info:
 * https://www.drupal.org/docs/8/multilingual/enable-language-negotiation.
 *
 * @see \language_language_types_info_alter()
 */
function oe_multilingual_url_suffix_language_types_info_alter(array &$language_types) {
  $language_types[LanguageInterface::TYPE_URL]['fixed'] = [LanguageNegotiationUrlSuffix::METHOD_ID, LanguageNegotiationUrlFallback::METHOD_ID];
}
