<?php

/**
 * @file
 * Contains hooks to manipulate language links for selection page.
 */

declare(strict_types = 1);

/**
 * Implements hook_page_preprocess().
 */
function oe_multilingual_selection_page_preprocess_language_selection_page_content(array &$variables): void {

  // Generate an array suitable for use in the ecl-language-list component.
  foreach ($variables['language_links']['#items'] as $key => $value) {
    $language_code = $key;
    $url = $value['#url']->toString();

    $variables['languages'][] = [
      'href' => $url,
      'hreflang' => $language_code,
      'label' => $value['#title'],
      'lang' => $language_code,
    ];
  }
}
